
APP_NAME = 'VRITTI'

# start_time is considered as 01-01-2010 epoch equivalent  = 1262304000000
START_OF_TIME = 1262304000  # 01-01-2010

#Binanace keys
API_KEY = ''
API_SECRET=''
coinbase= ''


#Reddit Keys
REDDIT_URL = 'https://www.reddit.com/prefs/apps'
REDDIT_CLIENT_ID = ''
REDDIT_SECRET = '-'
REDDIT_USERID = 'Ok-'
REDDIT_PASWWORD = ''


#Twitter_keys
TWITTER_API_KEY = ''
TWITTER_SECRET_KEY = ''
TWITTER_ACCESS_TOKEN = '-'
TWITTER_TOKEN_SECRET = ''
TWITTER_APP_NAME = ''

#DATA_ROOT_DIR = "z:\\crypto\\binance_historical_data\\"
DATA_ROOT_DIR ="/media/vamsi/Elements 8TB/crypto/binance_historical_data/1day/"

#Timescale login
TIMESCALE_USERNAME = ''
TIMESCALE_PASSWORD = ''
#TIMESCALE_HOST = '192.168.0.101'
TIMESCALE_HOST = 'localhost'
TIMESCALE_PORT = '5432'
TIMESCALE_MARKET_DATA_DB = 'market_data'

#kafka config:
STREAM_MARKET_DATA_KAFKA = False
STREAM_APP_LOG_KAFKA = False
KAFKA_BOOTSTRAP_SERVERS = ['']
KAFKA_MARKET_DATA_TOPIC = 'MARKET_DATA'
KAFKA_APP_LOG_TOPIC = 'APPLICATION_LOGS'
KAFKA_MARKET_NEWS_TOPIC = 'MARKET_NEWS'
KAFKA_ORDERS_TOPIC = 'ORDERS'
KAFKA_TRADES_TOPIC = 'TRADES'
KAFKA_TOPICS = [KAFKA_MARKET_DATA_TOPIC, KAFKA_APP_LOG_TOPIC, KAFKA_MARKET_NEWS_TOPIC,
                KAFKA_ORDERS_TOPIC, KAFKA_TRADES_TOPIC]